name: Java Maven CI with GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '20'

      - name: Install xmlstarlet
        run: |
          sudo apt update && sudo apt install xmlstarlet

      - name: Build with Maven
        id: maven
        run: mvn surefire-report:report test

      - name: Rename file for Git-Hub Pages
        run: mv ./target/site/surefire-report.html ./target/site/index.html

      - name: Check Test Results
        run: |
          for file in target/surefire-reports/*.xml; do
            if ! xmlstarlet sel -t -v "testsuite/@failures" -n "$file" | grep -q "0"; then
              echo "Tests failed."
              exit 1
            fi
            if ! xmlstarlet sel -t -v "testsuite/@errors" -n "$file" | grep -q "0"; then
              echo "Tests failed."
              exit 1
            fi
          done
          echo "Tests passed."

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: ${{ always() && github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site


